version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - .*
      exclude:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 24.5.0
        commands:
          - rm -rf ./node_modules
          - ''
          - ''
          - ''
          - npm config set registry https://registry.npmmirror.com
          - ''
          - ''
          - ''
          - 'npm install '
          - ''
          - ''
          - ''
          - npm install -g prisma
          - ''
          - ''
          - ''
          - npm run generate
          - ''
          - ''
          - ''
          - echo "Yes" | npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./.output
              - ./ecosystem.config.cjs
        strategy: {}
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: tencent
          hostID:
            - 650baa95-ee40-42ef-9c38-7d4a1942116f
        deployArtifact:
          - source: build
            name: lifeos-prod
            target: /gitee_go/deploy
            dependArtifact: BUILD_ARTIFACT
        script:
          - chmod +x /gitee_go/deploy/lifeos-prod.tar.gz
          - sudo chown -R ubuntu:ubuntu /html/9999/life-os && tar zxvf /gitee_go/deploy/lifeos-prod.tar.gz -C /html/9999/life-os 2>&1 > test.log
          - /home/ubuntu/.nvm/versions/node/v24.15.0/bin/node -v
          - chmod +x /html/9999/life-os/ecosystem.config.cjs
          - sudo chown -R ubuntu:ubuntu /home/ubuntu/.nvm/versions/node/v24.15.0/bin/pm2
          - sudo chown -R ubuntu:ubuntu /html/9999/life-os/ecosystem.config.cjs && /home/ubuntu/.nvm/versions/node/v24.15.0/bin/pm2 start /html/9999/life-os/ecosystem.config.cjs
          - ''
        notify: []
        strategy:
          retry: '0'
